"""
ChromaDB vector store wrapper for the 3GPP RAG pipeline.

Responsibilities:
  - Persist and load 384-dimensional embeddings generated by bge-small.
  - Add new chunks in batches to stay within ChromaDB's per-call limits.
  - Execute approximate nearest-neighbour queries and return raw results.
  - Expose simple stats (total chunk count) for the /health and /stats endpoints.

The collection is created automatically on first use. The database is stored
on disk under ``data/vectordb/`` (configurable via Settings.vector_db_path).

Compatibility note: requires chromadb>=0.5.0. The on-disk schema in this
project was created with a newer version; older 0.4.x clients are incompatible.
"""
import os
from pathlib import Path
from typing import List, Dict, Optional
import logging
import chromadb
from chromadb.config import Settings

logger = logging.getLogger(__name__)


class VectorStore:
    """Manage vector database operations with ChromaDB"""
    
    def __init__(
        self,
        persist_directory: str = "data/vectordb",
        collection_name: str = "3gpp_specs"
    ):
        """
        Initialize vector store
        
        Args:
            persist_directory: Directory to store the database
            collection_name: Name of the collection
        """
        self.persist_directory = Path(persist_directory)
        self.collection_name = collection_name
        
        # Create directory if it doesn't exist
        self.persist_directory.mkdir(parents=True, exist_ok=True)
        
        # Initialize ChromaDB client
        self.client = chromadb.PersistentClient(
            path=str(self.persist_directory)
        )
        
        # Get or create collection
        self.collection = self.client.get_or_create_collection(
            name=self.collection_name,
            metadata={"description": "3GPP technical specifications"}
        )
        
        logger.info(f"Initialized VectorStore: {collection_name}")
        logger.info(f"Persist directory: {self.persist_directory}")
    
    def add_chunks(self, chunks: List[Dict]) -> None:
        """
        Add chunks with embeddings to the vector store.

        Stores domain, generation, spec_number, and spec_title alongside the
        standard source/chunk_index fields so queries can be filtered by them.

        Args:
            chunks: List of chunks with 'text', 'embedding', and 'metadata' fields.
                    metadata may include: source, chunk_index, chunk_size,
                    domain, generation, spec_number, spec_title.
        """
        logger.info(f"Adding {len(chunks)} chunks to vector store")

        ids = []
        embeddings = []
        documents = []
        metadatas = []

        # Use current collection size as offset so IDs are globally unique
        # across multiple add_chunks() calls.
        id_offset = self.collection.count()
        for i, chunk in enumerate(chunks):
            chunk_id = f"id_{id_offset + i}"
            ids.append(chunk_id)
            embeddings.append(chunk['embedding'])
            documents.append(chunk['text'])

            meta = chunk.get('metadata', {})
            metadata = {
                "source":      meta.get('source', 'unknown'),
                "chunk_index": meta.get('chunk_index', i),
                "chunk_size":  meta.get('chunk_size', len(chunk['text'])),
                # Catalog fields — default to "unknown" so where-filters still work
                "domain":      meta.get('domain', 'unknown'),
                "generation":  meta.get('generation', 'unknown'),
                "spec_number": meta.get('spec_number', 'unknown'),
                "spec_title":  meta.get('spec_title', 'unknown'),
            }
            metadatas.append(metadata)

        # Add in batches (ChromaDB per-call limit)
        batch_size = 100
        for i in range(0, len(ids), batch_size):
            batch_end = min(i + batch_size, len(ids))
            self.collection.add(
                ids=ids[i:batch_end],
                embeddings=embeddings[i:batch_end],
                documents=documents[i:batch_end],
                metadatas=metadatas[i:batch_end],
            )
            logger.info(f"Added batch {i//batch_size + 1}/{(len(ids)-1)//batch_size + 1}")

        logger.info(f"Successfully added {len(chunks)} chunks")
    
    def query(
        self,
        query_embedding: List[float],
        n_results: int = 5,
        where_filter: Optional[Dict] = None,
    ) -> Dict:
        """
        Query the vector store with optional metadata filtering.

        Args:
            query_embedding: Embedding vector of the query.
            n_results: Number of results to return.
            where_filter: ChromaDB ``where`` clause to restrict results to a
                subset of chunks.  Examples::

                    {"domain": "RAN"}
                    {"generation": "5G"}
                    {"$and": [{"domain": "RAN"}, {"generation": "5G"}]}

        Returns:
            Dictionary with 'documents', 'metadatas', and 'distances'.
        """
        kwargs: Dict = {
            "query_embeddings": [query_embedding],
            "n_results": n_results,
        }
        if where_filter:
            kwargs["where"] = where_filter

        return self.collection.query(**kwargs)
    
    def get_stats(self) -> Dict:
        """Get statistics about the vector store"""
        count = self.collection.count()
        
        return {
            "collection_name": self.collection_name,
            "total_chunks": count,
        }
    
    def clear(self) -> None:
        """Clear all data from the collection"""
        logger.warning("Clearing all data from vector store")
        self.client.delete_collection(self.collection_name)
        self.collection = self.client.create_collection(
            name=self.collection_name
        )


if __name__ == "__main__":
    # Test the vector store
    logging.basicConfig(level=logging.INFO)
    
    # Initialize
    store = VectorStore()
    
    # Get stats
    stats = store.get_stats()
    print("\nVector Store Stats:")
    for key, value in stats.items():
        print(f"  {key}: {value}")